# Generated by Django 5.1.6 on 2025-03-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='not_started', max_length=20),
        ),
    ]
