# Generated by Django 4.2.12 on 2024-10-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='psychologicaltestresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='psychologicaltestresult',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='psychologicaltestresult',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='CourseMaterialPreference',
        ),
        migrations.DeleteModel(
            name='PsychologicalTestResult',
        ),
    ]
