# Generated by Django 4.2.12 on 2024-10-08 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnsys', '0002_alter_psychologicaltestresult_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRetakePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_retake', models.BooleanField(default=False, verbose_name='Может повторно пройти тест')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnsys.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Разрешение на повторное прохождение теста',
                'verbose_name_plural': 'Разрешения на повторное прохождение тестов',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
